### PR TITLE
fix show for BenchmarkConfig with id being nothing (fixes #78)

### LINKED ISSUE #78: error showing BenchmarkConfig
It seems the `BenchmarkConfig` prints `nothing` directly?

```julia
current = BenchmarkConfig(id=nothing, env = Dict("JULIA_NUM_THREADS"=>4), juliacmd=`julia -O3`)
```

This print gives an error in REPL.

### PR DESCRIPTION
**Pull request by johnnychen94**
fix issue https://github.com/JuliaCI/PkgBenchmark.jl/issues/78

### CODE REVIEW

File: src/benchmarkconfig.jl [hunk 1]
```diff
@@ -79,7 +79,7 @@ const _INDENT = "    "
 
 function Base.show(io::IO, bcfg::BenchmarkConfig)
     println(io, "BenchmarkConfig:")
-    println(io, _INDENT, "id: ", bcfg.id)
+    print(io, _INDENT, "id: "); show(bcfg.id); println("")
```
Comment (KristofferC) [inline src/benchmarkconfig.jl]:
```suggestion
    print(io, _INDENT, "id: "); show(bcfg.id); println()
```
